import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedPosMain {
  final List<PosMainModel> results;

  AutogeneratedPosMain({required this.results});

  factory AutogeneratedPosMain.fromJson(Map<String, dynamic> json) {
    var temp = <PosMainModel>[];
    if (json['results'] != null) {
      temp = <PosMainModel>[];
      json['results'].forEach((v) {
        temp.add(PosMainModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedPosMain(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['results'] = results.map((v) => v.toJson()).toList();
    return data;
  }
}

class PosMainModel extends Equatable {
  final int id;
  final String name;

  const PosMainModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory PosMainModel.fromJson(Map<String, dynamic> json) {
    return PosMainModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}
